[filter]                                                                                                                          
; enable filtering by file type, if not enabled
; then all the files will be copied and renamed
enabled = true
; set the required file types, if filter is enabled
; then this field is mandatory
file_types = .wav, .flac 

[core]
; base folder, destination folder, and new name prefix
base_dir = Music
dest_dir = Music2
name_prefix = file_

